AWSTemplateFormatVersion: "2010-09-09"
Resources:
    myInternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
          Tags:
          - Key: "Team"
            Value: "Infra"
          - Key: "Env"
            Value: "Test"
    myVPCInstance:
      Type: AWS::EC2::VPC
      Properties:
          CidrBlock: 10.0.0.0/16
          InstanceTenancy: default
          Tags:
           - Key: "Team"
             Value: "Infra"
           - Key: "Env"
             Value: "Test"
    mySubnet:
     Type: AWS::EC2::Subnet
     Properties:
       VpcId:
         Ref: myVPCInstance
       CidrBlock: 10.0.0.0/16
       AvailabilityZone: "us-east-1a"
       Tags:
       - Key: "Team"
         Value: "Infra"
       - Key: "Env"
         Value: "Test"
    mySubnet:
     Type: AWS::EC2::Subnet
     Properties:
       VpcId:
         Ref: myVPCInstance
       CidrBlock: 10.0.0.0/16
       AvailabilityZone: "us-east-1a"
       Tags:
       - Key: "Team"
         Value: "Infra"
       - Key: "Env"
         Value: "Test"
    myRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: myVPCInstance
        Tags:
        - Key: "Team"
          Value: "Infra"
        - Key: "Env"
          Value: "Test"
        - Key: "Name"
          Value: "MyRouteTable"