AWSTemplateFormatVersion: 2010-09-09
Resources: 
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            GroupDescription: Allow https access only to client host
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 443
                  ToPort: 443
                  CidrIp: 0.0.0.0/0
            Tags:
                - Key: "Team"
                  Value: "Dev"
                - Key: "Owner"
                  Value: "Example"
            
    