AWSTemplateFormatVersion: 2010-09-09
Parameters:
    MyBucketName:
        Type: String
    TeamTagValue:
        Type: String
    EnvTagValue:
        Type: String
Resources:
  MyTaggedBucket:   
    Type: AWS::S3::Bucket
    Properties: 
      BucketName:
        Ref: MyBucketName
      VersioningConfiguration:
        Status: Enabled
      Tags:
      - Key: "Team"
        Value: 
          Ref: TeamTagValue  
        Value: "Dev"
      - Key: "Env"
        Value:
          Ref: EnvTagValue