AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyBucket:   
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: "cloudformation-olga-test-bucket1"
      VersioningConfiguration:
        Status: Enabled